<?php

namespace Radic\Providers;

use Sebwite\Support\ServiceProvider;
use Sebwite\Support\Str;

/**
 * This is the ConsoleServiceProvider.
 *
 * @author        Sebwite
 * @copyright     Copyright (c) 2015, Sebwite
 * @license       https://tldrlegal.com/license/mit-license MIT
 * @package       Sebwite\Git
 */
class FirstRunServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $app = parent::boot(); // TODO: Change the autogenerated stub
        $c = app()->config;
        $firstRun = $c->get('first_run', true) === true;

        if($firstRun)
        {
           # artisan('first-run');
        }
        #$this->app->make('artisan')

        //if($config)
    }


    /**
     * Generate a random key for the application.
     *
     * @param  string  $cipher
     * @return string
     */
    protected function getRandomKey($cipher)
    {
        if ($cipher === 'AES-128-CBC') {
            return Str::random(16);
        }

        return Str::random(32);
    }

}
